name: tt_service
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  mask_text_input_formatter: ^2.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
  # images:
    - assets/images/imgLogo.png
    - assets/images/imgLogo2.png
    - assets/images/iconpoint.png
    - assets/images/iconBag1.png
    - assets/images/iconBag2.png
    - assets/images/iconBag3.png
    - assets/images/iconBag4.png
    - assets/images/imgTakeOut.png

  # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: GT-Eesti-Pro-Display
      fonts:
        - asset: assets/fonts/gteestiprodisplay_bold.otf
        - asset: assets/fonts/gteestiprodisplay_light.otf
        - asset: assets/fonts/gteestiprodisplay_medium.otf
        - asset: assets/fonts/gteestiprodisplay_regular.otf
        - asset: assets/fonts/gteestiprodisplay_thin.otf
        - asset: assets/fonts/gteestiprodisplay_ultrabold.otf